apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: docs
  namespace: openfaas-fn
spec:
  domain: "docs.clouderizer.com"
  function: "docs"
  ingressType: "nginx"
  bypassGateway: true
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-prod"
      # Change to ClusterIssuer if required
      # https://docs.cert-manager.io/en/latest/reference/clusterissuers.html
      # https://docs.cert-manager.io/en/latest/reference/issuers.html
      kind: "Issuer"