basic_auth: true

clusterRole: false
createCRDs: true

nodeSelector:
  beta.kubernetes.io/arch: arm64

gateway:
  image: openfaas/gateway:0.20.1-arm64
  directFunctions: true

oauth2Plugin:
  enabled: false

faasnetes:
  image: ghcr.io/openfaas/faas-netes:0.12.8

operator:
  image: ghcr.io/openfaas/faas-netes:0.12.8
  create: false

queueWorker:
  image: openfaas/queue-worker:0.11.2

prometheus:
  image: prom/prometheus:v2.11.0
  resources:
    requests:
      memory: "100Mi"

alertmanager:
  image: prom/alertmanager:v0.18.0

faasIdler:
  image: openfaas/faas-idler:0.4.0-arm64

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.20.1-arm64
  replicas: 1

ingressOperator:
  create: false

# Unfortunately the exporter is not multi-arch (yet)
nats:
  metrics:
    enabled: false
