---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-operator
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-operator
  template:
    metadata:
      labels:
        app: ingress-operator
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      serviceAccountName: ingress-operator
      containers:
      - name: operator
        image: openfaas/ingress-operator:0.6.6
        imagePullPolicy: Always
        command:
          - ./ingress-operator
        env:
        - name: ingress_namespace
          value: openfaas-fn
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 25Mi
