version: 1.0
provider:
  name: openfaas
  gateway: https://serverless.foo.com
functions:
  console:
    lang: dockerfile
    handler: ./console
    image: clouderizer/console:os 
    secrets:
      - dockerhub
      - sails-config
      - gcp-service-key
    readonly_root_filesystem: false
    environment:
        read_timeout: 1m
        write_timeout: 1m
        exec_timeout: 1m
        OPENFAAS_URL: https://test.serverless.clouderizer.com
  publishproject:
    lang: dockerfile
    handler: ./publishproject
    image: clouderizer/publishproject:opensource
    secrets:
      - dockerhub
      - gitlab
      - faas-secret-key
      - gcp-service-key
    readonly_root_filesystem: false
    environment:
        read_timeout: 1m
        write_timeout: 1m
        exec_timeout: 1m
        OPENFAAS_URL: https://test.serverless.clouderizer.com
  pmmlparser:
    lang: cldz_java11
    handler: ./pmmlparserbeta
    image: clouderizer/pmmlparser:opensource
    secrets:
      - dockerhub
    environment:
        read_timeout: 5m
        write_timeout: 5m
        exec_timeout: 5m
  h2oparser:
    lang: cldz_java11
    handler: ./h2oparser
    image: clouderizer/h2oparser:opensource
    secrets:
      - dockerhub
    environment:
        read_timeout: 5m
        write_timeout: 5m
        exec_timeout: 5m
