docker push clouderizer/cldz_baseimage:hotstart-python3-java11
docker push clouderizer/cldz_baseimage:hotstart-python3-java11-gpu
docker push clouderizer/cldz_baseimage:hotstart-tfpython3-java11
docker push clouderizer/cldz_baseimage:hotstart-torchpython3-java11
docker push clouderizer/cldz_baseimage:hotstart-python3
docker push clouderizer/cldz_baseimage:hotstart-python3-gpu
docker push clouderizer/cldz_baseimage:hotstart-tfpython3
docker push clouderizer/cldz_baseimage:hotstart-tfpython3-gpu
docker push clouderizer/cldz_baseimage:hotstart-torchpython3
docker push clouderizer/cldz_baseimage:hotstart-torchpython3-gpu